# version: "3"
services:
    api:
      build: .
      ports: 
          - 8000:8000
      env_file:
          - ./.env
#     postgres:
#       image:
#       environment:
#           env_file:
#               - ./.env
    
#     volumes:
#       - postgres-db:/var/lib/postgresql/data

# volume:
#   postgres-db:
